export const RECEIVE_PHOTOS = "RECEIVE_PHOTOS";
export const REQUEST_PHOTOS = "REQUEST_PHOTOS";

export const REQUEST_PAGINATION = "REQUEST_PAGINATION";

export const REQUEST_SEARCH_PHOTOS = "REQUEST_SEARCH_PHOTOS";
export const RECEIVE_SEARCH_PHOTOS = "RECEIVE_SEARCH_PHOTOS";

