export const RECEIVE_PHOTOS = "RECEIVE_PHOTOS";
export const REQUEST_PHOTOS = "REQUEST_PHOTOS";

export const RECEIVE_PAGINATION = "RECEIVE_PAGINATION";
export const REQUEST_PAGINATION = "REQUEST_PAGINATION";