// PHOTOS
export const RECEIVE_PHOTOS = "RECEIVE_PHOTOS";
export const REQUEST_PHOTOS = "REQUEST_PHOTOS";


export const REQUEST_SEARCH_PHOTOS = "REQUEST_SEARCH_PHOTOS";
export const RECEIVE_SEARCH_PHOTOS = "RECEIVE_SEARCH_PHOTOS";


// COLLECTIONS
export const RECEIVE_COLLECTIONS = "RECEIVE_COLLECTIONS";
export const REQUEST_COLLECTIONS = "REQUEST_COLLECTIONS";

export const REQUEST_SEARCH_COLLECTIONS = "REQUEST_SEARCH_COLLECTIONS";
export const RECEIVE_SEARCH_COLLECTIONS = "RECEIVE_SEARCH_COLLECTIONS";


// GENERAL TYPES
export const REQUEST_PAGINATION = "REQUEST_PAGINATION";
export const REQUEST_PAGINATION_TYPE = "REQUEST_PAGINATION_TYPE";
